### PR TITLE
SIT782 - Sprint 2 - code updates

### PR DESCRIPTION
**Pull request by BlackPanther73**
CSS Changes, Firebase google authentication and bug fixes.

### CODE REVIEW

**Comment by jakerenzella** [comment]
I am going to go through here and cherry-pick what I can, @lapnguyen-se what's the status of the cookies commit, is that working?

**Comment by stevennguyen-se** [comment]
Yes, It is working. The website now will store the latest iteration and use
that to render the corresponding tutorial when users refresh or reopen the
web.

**Comment by jakerenzella** [comment]
Does it require firebase for that?

**Comment by stevennguyen-se** [comment]
No. It just need a "iron-cookie": "wincinderith/iron-cookie#^1.0.0" to run.

**Comment by jakerenzella** [comment]
@lapnguyen-se pulled 👍

**Comment by jakerenzella** [comment]
OK everyone, I think I have merged as much as I can here. I had to clone this PR and cherry-pick the specific commits as I went, so although this is marked as "not merged" it technically has been, I will make sure Leonard knows this.

**Pull request closed without merging**
